name: Frontend CD

on:
  push:
    branches: [ "master" ]
#     paths: 
#       - "/frontend"
  pull_request:
    branches: [ "master" ]
#     paths: 
#       - "/frontend"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_FRONTEND_STAGING}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          dontautocreate: true
          branch: master
          appdir: "frontend"
